# Generated by Django 3.2.12 on 2022-11-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('lugar', models.CharField(max_length=50)),
                ('puntuacion', models.FloatField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=500, null=True)),
                ('pendiente', models.BooleanField()),
            ],
        ),
    ]
