# Generated by Django 3.2.12 on 2022-11-26 14:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0002_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='ubicacion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
