# Generated by Django 3.2.12 on 2022-11-26 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lugares', '0003_restaurante_ubicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
