# Generated by Django 3.2.12 on 2022-11-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('subgenero', models.CharField(max_length=200)),
                ('publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('lectura', models.DateField(verbose_name='Fecha de lectura')),
                ('puntuacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('subgenero', models.CharField(max_length=200)),
                ('estreno', models.DateField(verbose_name='Fecha de estreno')),
                ('visualizacion', models.DateField(verbose_name='Fecha de visualización')),
                ('puntuacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('subgenero', models.CharField(max_length=200)),
                ('estreno', models.DateField(verbose_name='Fecha de estreno')),
                ('visualizacion', models.DateField(verbose_name='Fecha de visualización')),
                ('puntuacion', models.FloatField()),
            ],
        ),
    ]
