# Generated by Django 3.2.12 on 2022-11-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='leido',
            field=models.BooleanField(default=False, verbose_name=False),
            preserve_default=False,
        ),
    ]
