# Generated by Django 3.2.12 on 2022-11-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0002_libro_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='leido',
            field=models.BooleanField(),
        ),
    ]
