# Generated by Django 3.2.12 on 2022-11-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0003_alter_libro_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='vista',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='vista',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
