# Generated by Django 3.2.12 on 2022-11-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0010_alter_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
        migrations.AddField(
            model_name='serie',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='subgenero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='director',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serie',
            name='genero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='serie',
            name='subgenero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
