# Generated by Django 3.2.12 on 2022-11-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalogo', '0011_auto_20221107_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='temporada',
            field=models.IntegerField(null=True),
        ),
    ]
